AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template Route53 Aphrodite

# Parameters:
#   Name:
#     Description: Frontend Name
#     Type: String

Parameters:
  DomainMainName:
    Type: String
    Default: aphrodite.world

  HostedZoneId:
    Type: String
    Default: Z09226481WGGUC2SQR8OB

Resources:
  RecordSetGroupAphroditeWorld:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      HostedZoneId: Z09226481WGGUC2SQR8OB
      #Name: !Ref DomainMainName
      #Comment: String
      #HostedZoneName: s3-website.us-east-2.amazonaws.com
      RecordSets: 
        - AliasTarget: 
            DNSName: s3-website.us-east-2.amazonaws.com
            EvaluateTargetHealth: true
            HostedZoneId: Z2O1EMRO9K5GLX
          Name: test2.aphrodite.world
          SetIdentifier: Z09226481WGGUC2SQR8OB
          #TTL: "60"
          Type: A
          #Comment: String
          #Failover: String
          #GeoLocation: 
            #ContinentCode: NA
            #CountryCode: US
            #SubdivisionCode: String
          #HealthCheckId: String
          #HostedZoneId: Z2O1EMRO9K5GLX
          #HostedZoneName: s3-website.us-east-2.amazonaws.com
          #MultiValueAnswer: Boolean
          #Region: us-east-2
          #ResourceRecords: 
          #  - test.aphrodite.world
          Weight: 100
