AWSTemplateFormatVersion: 2010-09-09
Description: >
  Template Route53 Aphrodite

# Parameters:
#   Name:
#     Description: Frontend Name
#     Type: String

Parameters:
  DomainMainName:
    Type: String
    Default: aphrodite.world

  HostedZoneId:
    Type: String
    Default: Z09226481WGGUC2SQR8OB

Resources:
  LogGroupRoute53:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /aws/route53/springhome.com.br
      RetentionInDays: 3

  RoleForlogGroupRoute53:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: route53.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonRoute53FullAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchFullAccess'
      RoleName: !Join
        - '-'
        - - route53
          - !Ref 'AWS::Region'      

  PolicyForlogGroupRoute53:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
             - logs:PutLogEvents
             - logs:CreateLogStream
            Resource: 'arn:aws:logs:*'
      PolicyName: aws-route53-springhome.com.br # !Ref LogGroupRoute53
      Roles:
        - !Ref RoleForlogGroupRoute53          

  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      HostedZoneConfig: 
        Comment: Config Zone Main
      HostedZoneTags: 
        - Key: Region
          Value: Ohio-US
      Name: springhome.com.br
      QueryLoggingConfig: 
        CloudWatchLogsLogGroupArn: !GetAtt
          - LogGroupRoute53
          - Arn      
        #CloudWatchLogsLogGroupArn: arn:aws:logs:us-east-1:241621294044:log-group:/aws/route53/springhome.com.br:* #!GetAtt LogGroupRoute53.Arn
      #VPCs: 
      #  - VPCId: vpc-0ec8d4736dccb5506
      #    VPCRegion: us-east-1

  Route53RecordSetGroupAphroditeWorld:
    Type: AWS::Route53::RecordSetGroup
    Properties: 
      HostedZoneId: !GetAtt Route53HostedZone.CanonicalHostedZoneID
      #Name: !Ref DomainMainName
      #Comment: String
      #HostedZoneName: s3-website.us-east-2.amazonaws.com
      RecordSets: 
        - AliasTarget: 
            DNSName: s3-website.us-east-2.amazonaws.com
            EvaluateTargetHealth: true
            HostedZoneId: Z2O1EMRO9K5GLX
          Name: dev.springhome.com.br #test.aphrodite.world
          SetIdentifier: dev.springhome.com.br #test.aphrodite.world
          Type: A
          Weight: 100
        # - AliasTarget: 
        #     DNSName: s3-website.us-east-1.amazonaws.com
        #     EvaluateTargetHealth: true
        #     HostedZoneId: Z2O1EMRO9K5GLX
        #   Name: hom.aphrodite.world
        #   SetIdentifier: hom.aphrodite.world
        #   #TTL: "60"
        #   Type: A
        #   Weight: 100          
          #Comment: String
          #Failover: String
          #GeoLocation: 
            #ContinentCode: NA
            #CountryCode: US
            #SubdivisionCode: String
          #HealthCheckId: String
          #HostedZoneId: Z2O1EMRO9K5GLX
          #HostedZoneName: s3-website.us-east-2.amazonaws.com
          #MultiValueAnswer: Boolean
          #Region: us-east-2
          #ResourceRecords: 
          #  - test.aphrodite.world
          
