name: Rollback - Infra as Code - Route 53

on: 
  push:
    branches:
      - rollback

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Deploy to AWS CloudFormation
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: MyStack
      #     template: myStack.yaml
      #     parameter-overrides: "MyParam1=myValue,MyParam2=${{ secrets.MY_SECRET_VALUE }}"          

      # https://github.com/marketplace/actions/aws-cloudformation-deploy-cloudformation-stack-action-for-github-actions

      - name: UnDeploy
        run: |
            echo "Delete Stack"